#!/usr/bin/env bash

case "$1" in
    docker)
        echo "### building ocn2pid service docker ###"
        docker build -f target/docker/Dockerfile --pull --no-cache . -t docker-metascrum.artifacts.dbccloud.dk/ocn2pid-service:devel || exit 1
        if [[ ! -z "$BUILD_NUMBER" ]]; then
            docker tag docker-metascrum.artifacts.dbccloud.dk/ocn2pid-service:devel docker-metascrum.artifacts.dbccloud.dk/ocn2pid-service:${BRANCH_NAME}-${BUILD_NUMBER}
        fi
        ;;

    *)
        echo "### building ocn2pid project ###"
        echo "### Look for build artifacts in target/ ###"

        mvn package -Dmaven.test.skip=true || exit 1
        ;;
esac

